const inputActionTypes = {
  ADD: 'ADD_INPUT',
  CLOSE_ADD_DIALOG: 'CLOSE_ADD_DIALOG_INPUT',
  DELETE: 'DELETE_INPUT',
  OPEN_ADD_DIALOG: 'OPEN_ADD_DIALOG_INPUT',
  REORDER: 'REORDER_INPUT'
};

export default inputActionTypes;
