const textareaActionTypes = {
  ADD: 'ADD_TEXTAREA',
  CLOSE_ADD_DIALOG: 'CLOSE_ADD_DIALOG_TEXTAREA',
  DELETE: 'DELETE_TEXTAREA',
  OPEN_ADD_DIALOG: 'OPEN_ADD_DIALOG_TEXTAREA',
  SET: 'SET_TEXTAREA'
};

export default textareaActionTypes;
